name: "text_encoder"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  { name: "INPUT_IDS" data_type: TYPE_INT64 dims: [ 192 ] },
  { name: "ATTENTION_MASK" data_type: TYPE_INT64 dims: [ 192 ] }
]
output [ { name: "EMBEDDING" data_type: TYPE_FP32 dims: [ 1024 ] } ]
instance_group [ { kind: KIND_CPU } ]
